# Generated by Django 5.2.4 on 2025-07-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_bet_point_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attacker_point_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='defender_point_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
